---
framework: jest
preRun:
  command:
    - npm install
    - npm run build
    - node test/prepare-jest.js
  env:
    TEST_BACKEND: 1
    
postMerge:
  pattern: 
    - "./test/backend.spec.js"
configFile: "./config/jest-backend.config.js"
version: 1.0
